excluded:
- Carthage/
- Pods/
- Scripts/
- SubscMemo/Generated/

disabled_rules:
- trailing_whitespace
- multiple_closures_with_trailing_closure

identifier_name:
  min_length: 2

nesting:
  type_level: 3

line_length: 200
