name: SubscMemo

options:
  # プリフィクスを指定すると、各ターゲットのバンドルIDが自動で「{プリフィクス}.{ターゲット名}」に設定される
  bundleIdPrefix: com.yyokii
  deploymentTarget:
    iOS: 14.0
  xcodeVersion: "12.0"
  # findCarthageFrameworks: true # 余計なフレームワークまで追加されてしまうためコメントアウト
  carthageExecutablePath: mint run Carthage/Carthage carthage

packages:
  Rswift:
    url: https://github.com/mac-cain13/R.swift.Library
    version: 5.2.0
  Tagged:
    url: "https://github.com/pointfreeco/swift-tagged.git"
    version: 0.5.0

  # import 効かないのでpodでやる
  # Resolver:
  #   url: https://github.com/hmlongco/Resolver.git
  #   version: 1.1.2

targets:
  SubscMemo:
    type: application
    platform: iOS
    sources:
      - SubscMemo
      - path: "SubscMemo/Generated/R.generated.swift"
        optional: true
        type: file
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: SubscMemo/SubscMemo.entitlements
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: SubscMemo/Info.plist
        MARKETING_VERSION: 1.0.0 
        OTHER_LDFLAGS: -fprofile-instr-generate
    dependencies:
      - package: Rswift
      - package: Tagged
    preBuildScripts:
      - script: |
                if mint list | grep -q 'R.swift'; then
                  xcrun --sdk macosx mint run R.swift rswift generate "$SRCROOT/$TARGET_NAME/Generated/R.generated.swift"
                else
                  echo "error: R.swift not installed; run 'mint bootstrap' to install"
                  return -1
                fi
        name: Generate Resources with R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/$TARGET_NAME/Generated/R.generated.swift
      - script: |
                mint run swiftformat
        name: Run Swiftformat
    postCompileScripts:
      - script: |
                if which mint >/dev/null; then
                  mint run swiftlint swiftlint autocorrect --format
                  mint run swiftlint swiftlint
                else
                  echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
                fi
        name: Run SwiftLint
  SubscMemoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SubscMemoTests
    settings:
      base:
        INFOPLIST_FILE: SubscMemoTests/Info.plist
        # PRODUCT_BUNDLE_IDENTIFIER: {Bundle ID Prefix}.SubscMemoTests
    dependencies:
      - target: SubscMemo

  SubscMemoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - SubscMemoUITests
    settings:
      base:
        INFOPLIST_FILE: SubscMemoUITests/Info.plist
        # PRODUCT_BUNDLE_IDENTIFIER: {Bundle ID Prefix}.SubscMemoUITests
    dependencies:
      - target: SubscMemo

schemes:
  SubscMemo:
    build:
      targets:
        SubscMemo: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - SubscMemo
      targets:
        - name: SubscMemoTests
          parallelizable: true
          randomExecutionOrder: true
        - name: SubscMemoUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
