name: SubscMemo

options:
  deploymentTarget:
    iOS: 14.3
  xcodeVersion: "12.0"
  # findCarthageFrameworks: true # 余計なフレームワークまで追加されてしまうためコメントアウト
  carthageExecutablePath: mint run Carthage/Carthage carthage

packages:
  Tagged:
    url: "https://github.com/pointfreeco/swift-tagged.git"
    version: 0.5.0

  # import 効かないのでpodでやる
  # Resolver:
  #   url: https://github.com/hmlongco/Resolver.git
  #   version: 1.1.2

targets:
  SubscMemo:
    type: application
    platform: iOS
    sources:
      - SubscMemo
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: SubscMemo/SubscMemo.entitlements
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_LANGUAGE: jp
        DEVELOPMENT_TEAM: EAZT2D654U
        DISPLAY_NAME: マイサブスク
        INFOPLIST_FILE: SubscMemo/Info.plist
        MARKETING_VERSION: 1.0.0 
        OTHER_LDFLAGS: -fprofile-instr-generate $(inherited)
        PRODUCT_BUNDLE_IDENTIFIER: com.yyokii.mysubscmemo
        TARGETED_DEVICE_FAMILY: 1
    dependencies:
      - target: SubscMemoWidget
      - package: Tagged
    preBuildScripts:
      - script: |
                mint run swiftformat
        name: Run Swiftformat
    postCompileScripts:
      - script: |
                if which mint >/dev/null; then
                  mint run swiftlint swiftlint autocorrect --format
                  mint run swiftlint swiftlint
                else
                  echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
                fi
        name: Run SwiftLint

  SubscMemoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SubscMemoTests
    settings:
      base:
        INFOPLIST_FILE: SubscMemoTests/Info.plist
        # PRODUCT_BUNDLE_IDENTIFIER: {Bundle ID Prefix}.SubscMemoTests
    dependencies:
      - target: SubscMemo

  SubscMemoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - SubscMemoUITests
    settings:
      base:
        INFOPLIST_FILE: SubscMemoUITests/Info.plist
        # PRODUCT_BUNDLE_IDENTIFIER: {Bundle ID Prefix}.SubscMemoUITests
    dependencies:
      - target: SubscMemo

  SubscMemoWidget: # Widget Extension
    type: app-extension
    platform: iOS
    settings:
      base:
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        CODE_SIGN_ENTITLEMENTS: SubscMemoWidget/SubscMemoWidget.entitlements
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: EAZT2D654U
        INFOPLIST_FILE: SubscMemoWidget/Info.plist
        MARKETING_VERSION: 1.0.0 
        PRODUCT_BUNDLE_IDENTIFIER: com.yyokii.mysubscmemo.SubscMemoWidget
        PRODUCT_NAME: $(TARGET_NAME)
        SKIP_INSTALL: true
    sources:
      - SubscMemoWidget
      - path: "SubscMemo/Extention/UserDefaults+Base.swift"
        type: file
      - path: "SubscMemo/Extention/KeyNameSpaceable.swift"
        type: file
      - path: "SubscMemo/UI/Styleguide"
        type: group
      - path: "SubscMemo/UI/ViewHelper"
        excludes: 
          - "View+HideKeyboard.swift"
        type: group
    dependencies:
      - package: Tagged
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework

schemes:
  SubscMemo:
    build:
      targets:
        SubscMemo: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - SubscMemo
      targets:
        - name: SubscMemoTests
          parallelizable: true
          randomExecutionOrder: true
        - name: SubscMemoUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
